# Build stage
FROM alpine

# set working directory
WORKDIR /app

COPY . .

# Add protoc
RUN apk update && \
    apk upgrade && \
    apk add protoc

# Generate
RUN protoc --proto_path=src/Protos --csharp_out=src/Protos --csharp_opt=file_extension=.cs,base_namespace=EntitiesV1 src/Protos/entities_v1.proto